#mv sources/* .
#rm -rf sources
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_atoi.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_bzero.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_calloc.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_isalnum.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_isalpha.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_isascii.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_isdigit.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_isprint.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_itoa.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_memccpy.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_memchr.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_memcmp.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_memcpy.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_memmove.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_memset.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_putchar_fd.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_putendl_fd.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_putnbr_fd.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_putstr_fd.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_split.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strchr.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strdup.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strjoin.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strlcat.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strlcpy.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strlen.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strmapi.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strncmp.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strnstr.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strrchr.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_strtrim.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_substr.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_tolower.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change ft_toupper.c
#change() { cat $1 | sed 's/\.\.\///g' > oxi; cp oxi $1; }; change main.c